### PR TITLE
Doc/architecture diagram

### PR DESCRIPTION
**Pull request by oed**
NOTE: this should be merged after #91 

Please only review the architecture diagram that is in the README for this PR.

### CODE REVIEW

**Comment by dazuck** [comment]
@oed my comments (keep in mind i'm not super familiar with technical diagrams) 
B - "request data from user 3box via [what is the method]? 
C2 - where is the link between address and profile stored? 
D - the IPFS doc is a single doc containing all mappings (address<>hashes) right, or one per 3Box? 
E - what is the root hash tracker? what role does it play later?

**Comment by christianlundkvist** [comment]
@oed Looks good! One question I have is about the Orbit-DB instances. Are we sure the KV-store is the right data structure for the private data? The unencrypted data might be in a KV-store but it’s note clear that the encrypted data is best defined this way. What would be the keys and what would be the values?

**Comment by michaelsena** [comment]
Have we considered EAV (entity-attribute-value) at all for the structure, since multiple entities could try to write the same attribute (ie same username attribute)? Or is this need taken care of by namespacing? I just saw something about it in another Medium post (maybe about Graph.io).

@christianlundkvist I would guess the keys need to contain the information necessary to index the values, which are hashes of individually encrypted data?

**Comment by oed** [comment]
@dazuck Good questions, I'll make some improvements to the description and some clarifications here.
B - This is only meant to be a high level overview. Details of methods etc should be in the `3box-js` spec.
C2 - It's stored in the hash tracker, see F1
D - no, each user has their own ipfs objcect, the mappings are stored in the hash tracker. Clarifying this in the readme.
E. The root hash tracker keeps track of all users latest hashes for their data stores. Hopefully we can decentralize this as much as possible in the future (already have some plans for that, but nothing that we should focus on right now). 
Can you take a look and see if the description I added to the readme helps?

@christianlundkvist Right, I might have oversimplified this in my head. Can we schedule a call today to discuss, with @c-castillo as well.

@michaelsena I don't think we have considered it in the MVP no. Currently we have no way of distinguishing entities (dapps) since we have no way to authenticate that. This will change once we move to the iframe method.

**Comment by dazuck** [comment]
@oed sorry didn't see your comments before. looks great to me!

**Pull request merged**
