### PR TITLE
Added best practices documentation for repo maintainence

### PR DESCRIPTION
**Pull request by oed**

### CODE REVIEW

**Comment by c-castillo** [comment]
@oed I think it's a good idea to provide a "publishing script", doing the following:
- run tests
- lint
- npm run build
- git tag
- bump version
- npm publish

**Comment by oed** [comment]
@c-castillo I'm not sure about all of them. Once things are in master, we already know that:
* tests passes
* linter passes
* version is bumped

I could add git tag to the prepublishOnly hook though :)

**Comment by oed** [comment]
hm, it's non-trivial to the the version number to git in the hook though. @c-castillo if you feel like making a script, create a story for it an we can maybe do it some other sprint?

**Comment by c-castillo** [comment]
Yes, we can automate things as needed in the future. But let's wait to have our pain points more defined to automate those.

**Pull request merged**
